# Generated by Django 4.2.4 on 2023-11-15 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('cloud_image_url', models.URLField()),
                ('action', models.URLField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.section')),
            ],
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
